### ISSUE TITLE
fix(dashboard): check if import still works

### ISSUE THREAD

**Issue by rap2hpoutre** [SocialGouv/mano#508]
j'ai téléchargé l'exemple et importé et ça semble planter, il faut que je creuse.

**Comment by arnaudambro** [comment]
probablement lié à mon `createdAT`, j'y avais pensé mais j'ai rien fait

**Comment by arnaudambro** [comment]
non aucun rapport, mais c'est pété
```
TypeError: Cannot add property options, object is not extensible
    at ImportData.js:82:1
    at Array.map (<anonymous>)
    at onParseData (ImportData.js:76:1)
```

**Comment by arnaudambro** [comment]
#530
